#!/usr/bin/env bash

PROJECT_NAME="GodsOfDeceit"
ENGINE_DIRECTORY="/opt/UnrealEngine"
ANDROID_CLI="/opt/bin/android-cli.sh"
PROJECT_DIRECTORY=`dirname $(dirname $(realpath "$0"))`
PROJECT_FILE="${PROJECT_DIRECTORY}/${PROJECT_NAME}.uproject"
UE4_EDITOR_WORKING_DIRECTORY="${ENGINE_DIRECTORY}/Engine/Binaries/Linux/"
UE4_EDITOR_EXECUTABLE="${UE4_EDITOR_WORKING_DIRECTORY}/UE4Editor"
UE4_EDITOR_COMMAND_LINE_ARGUMENTS="\"${PROJECT_FILE}\" -opengl4"
LD_LIBRARY_PATH=":.:"

cd "${UE4_EDITOR_WORKING_DIRECTORY}" \
    && source "${ANDROID_CLI}" \
    && ${UE4_EDITOR_EXECUTABLE} ${UE4_EDITOR_COMMAND_LINE_ARGUMENTS}
